packages:
  - packages/*
  - website

onlyBuiltDependencies:
  - sqlite3

patchedDependencies:
  '@changesets/assemble-release-plan': patches/@changesets__assemble-release-plan.patch
  rspress-plugin-og: patches/rspress-plugin-og.patch
