packages:
  - packages/*
  - website

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: false
  sqlite3: false
  unrs-resolver: false

overrides:
  'rspress-plugin-og>@rspress/shared': '-'
  'rspress-plugin-og>rspress': '-'

packageExtensions:
  'rspress-plugin-og':
    dependencies:
      rslog: '^2.0.0'

patchedDependencies:
  '@changesets/assemble-release-plan': patches/@changesets__assemble-release-plan.patch
  rspress-plugin-og: patches/rspress-plugin-og.patch
