packages:
  - packages/*
  - website

patchedDependencies:
  '@changesets/apply-release-plan': patches/@changesets__apply-release-plan.patch
  '@changesets/assemble-release-plan': patches/@changesets__assemble-release-plan.patch
